language: swift
os: osx
osx_image: xcode12.1

script:
- xcodebuild -workspace DeliriumOver.xcworkspace -scheme DeliriumOver -derivedDataPath Build/ -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 8 Plus' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- ./checkCoverage 0.7
