language: swift
os: osx
osx_image: xcode12.1

xcode_workspace: DeliriumOver.xcworkspace
xcode_scheme: DeliriumOver
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone 8 Plus

after_success:
- ./checkCoverage 0.7
