language: swift
os: osx
#xcode_project: DeliriumOver.xcodeproj # path to your xcodeproj folder
#xcode_scheme: DeliriumOver
#xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone 8 Plus

script:
 - set -o pipefail
 - xcodebuild -workspace DeliriumOver.xcworkspace -scheme DeliriumOver -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c