#!/bin/bash

coverage=`xcrun xccov view --report --json Build/Logs/Test/*.xcresult | cut -d',' -f2 | cut -d':' -f2`
threshold=$1

if (( $(echo "$coverage < $threshold" |bc -l) )); then
	echo "Current coverage is below threshold! Coverage: $coverage. Threshold: $threshold"
	exit -1
fi

